name: Deployment pipeline

on:
  push:
    branches:
      - main
      # note that your "main" branch might be called main instead of master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3 # uses keyword tells the workflow to run a specific action
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Directory content
        run: |
          ls -l
      - name: npm install backend
        run: cd ./phonebook-backend && npm install
      # - name: Directory content after using cd in previous command
      #   run: |
      #     ls -l
      - name: npm install frontend
        run: cd ./phonebook-frontend && npm install
      - name: npm lint
        run: cd ./phonebook-backend && npm run lint
      - name: build
        run: cd ./phonebook-backend && npm run build:ui
      - name: e2e tests
        uses: cypress-io/github-action@v4
        with:
          project: ./phonebook-backend
          build: cd ./phonebook-backend && npm run build:ui
          start: cd ./phonebook-backend && npm run start
          wait-on: 'http://localhost:3001'
